# This is a basic workflow to help you get started with Actions

name: Run Robot Framework API Tests - Dog API 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout código
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Runs a set of commands using the runners shell
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar testes Robot
        run: |
          robot -d results test/api 

      - name: Publicar Relatórios como Artefatos
        uses: actions/upload-artifact@v3
        with:
          name: robot-test-results
          path: results
